# TODO: make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'python-template'
description: 'Sum 2 numbers and a little extra'
branding: # TODO: choose yours from https://github.com/haya14busa/github-action-brandings
  icon: 'book-open'
  color: 'green'
# TODO: update with your inputs and outputs
inputs:
  number-one:  
    description: 'Choose a number'
    required: false
  number-two:
    description: 'Choose another number'
    required: false
outputs:
  sum:
    description: 'Sum of both numbers, if provided - a joke otherwise'
runs:
  using: 'docker'
  image: docker://ghcr.io/fopina/action-python-template:latest
  # image: 'Dockerfile'
